# Generated by Django 6.0.2 on 2026-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_remove_post_location_post_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('writter', 'Escritor'), ('reader', 'Lector')], default='reader', max_length=20),
        ),
    ]
