# Generated by Django 6.0.2 on 2026-04-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
