export const DICTIONARY = [
    { word: "MANZANILLO", desc: "Principal puerto marítimo de México en el Pacífico, clave para el comercio internacional"},
    { word: "COLIMA", desc: "Estado al que pertenece Manzanillo"},
    { word: "PUERTO", desc: "Infraestructura central de la ciudad que impulsa la economía mediante comercio marítimo" },
    { word: "SANTIAGO", desc: "Área tradicional y turística con playas y desarrollos hoteleros" },
    { word: "SALAGUA", desc: "Zona urbana moderna con crecimiento residencial y comercial" },
    { word: "LASBRISAS", desc: "Sector cercano al puerto, vinculado a actividades industriales" },
    { word: "MIRAMAR", desc: "Playa extensa popular entre locales y turistas por su ambiente relajado" },
    { word: "PESCA", desc: "Actividad tradicional que forma parte de la identidad local" },
    { word: "MARISCOS", desc: "Base de la gastronomía títpica de la región costera" },
    { word: "PEZVELA", desc: "Especie emblemática que atrae turismo deportivo internacional" },
    { word: "TURISMO", desc: "Sector económico impulsado por playas, clima y cultura" },
    { word: "PLAYA", desc: "Principal atractivo natural de la ciudad" },
    { word: "AUDIENCIA", desc: "Bahía tranquila ideal para nadar y practicar deportes acuáticos" },
    { word: "CENTRO", desc: "Zona donde se concentran edificios antiguos y vida tradicional" },
    { word: "BOULEVARD", desc: "Vía principal que conecta zonas turísticas y residenciales" },
    { word: "TATEMADO", desc: "Comida tradicional manzanillence elaborada en base de carne de cerdo y chiles secos" },
    { word: "POZOLESECO", desc: "Una versión especial de pozole sin caldo, muy popular en la región" },
    { word: "ATUN", desc: "Producto relevante en pesca comercial" },
    { word: "ADUANA", desc: "Control de mercancías" },
    { word: "TRENES", desc: "Transporte que se vincula directamente con el puerto de Manzanillo" },
    { word: "CUYUTLAN", desc: "Laguna cercana a Manzanillo que contiene gran valor ecológico" },
    { word: "BARCELO", desc: "Hotel más grande de Manzanillo" },
    { word: "MANUEL", desc: "Haz encontrado el EasterEgg, soy un dev de ManzaLife" },
    { word: "VALENTIN", desc: "Haz encontrado el EasterEgg, soy un dev de ManzaLife" },
    { word: "AXL", desc: "Haz encontrado el EasterEgg, soy un dev ManzaLife" },
    { word: "BRIAN", desc: "Haz encontrado el EasterEgg, soy un dev de ManzaLife" },
    { word: "GRECO", desc: "Haz encontrado el EasterEgg, soy un dev de ManzaLife" }
]
