export { default as Home } from "./Home/Home"
export { default as Login } from "./Login/Login"
export { default as Register } from "./Register/Register.jsx"
export { default as BlogHome } from "./Blog/BlogHome.jsx"
export { default as Pruebas } from "./PaginaPruebas/Pruebas.jsx"
export { default as CreatePost } from "./CreatePost/CreatePost.jsx"
export { default as BlogCategories } from "./Blog/BlogCategories.jsx"
export { default as BlogCommunity } from "./Blog/BlogCommunity.jsx"
export { default as BlogProfile } from "./Blog/BlogProfile.jsx"
export { default as BlogPostDetail } from "./Blog/BlogPostDetail.jsx"
// export { default as BlogPostDetail } from "./Blog/BlogPostDetail.jsx"
export { default as ManzaDle } from "./ManzaDle/ManzaDle.jsx"