export { default as Home } from "./Home/Home"
export { default as Login } from "./Login/Login"
export { default as Register } from "./Register/Register.jsx"
export { default as BlogHome } from "./Blog/BlogHome.jsx"
export { default as Pruebas } from "./PaginaPruebas/Pruebas.jsx"
// export { default as Posts } from "./Posts/Posts.jsx"